// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrydo7cnokzOt9rk5-qrxTIr9b1yzyRg',
    appId: '1:594940567388:web:1c3300c56ea69936a12b99',
    messagingSenderId: '594940567388',
    projectId: 'expense-db-165fe',
    authDomain: 'expense-db-165fe.firebaseapp.com',
    storageBucket: 'expense-db-165fe.firebasestorage.app',
    measurementId: 'G-F76CJJCYHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoL7tIdLwU-Ea4EPjPeOZ9dOLzxlMxTJM',
    appId: '1:594940567388:android:9c1af5e8ed9dc26da12b99',
    messagingSenderId: '594940567388',
    projectId: 'expense-db-165fe',
    storageBucket: 'expense-db-165fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Ylof9WMmbtFMFhRSunoNIQ32kJPKEwc',
    appId: '1:594940567388:ios:a0c6f2c8efa242c2a12b99',
    messagingSenderId: '594940567388',
    projectId: 'expense-db-165fe',
    storageBucket: 'expense-db-165fe.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Ylof9WMmbtFMFhRSunoNIQ32kJPKEwc',
    appId: '1:594940567388:ios:a0c6f2c8efa242c2a12b99',
    messagingSenderId: '594940567388',
    projectId: 'expense-db-165fe',
    storageBucket: 'expense-db-165fe.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtrydo7cnokzOt9rk5-qrxTIr9b1yzyRg',
    appId: '1:594940567388:web:e3f5cd8f0f278f5fa12b99',
    messagingSenderId: '594940567388',
    projectId: 'expense-db-165fe',
    authDomain: 'expense-db-165fe.firebaseapp.com',
    storageBucket: 'expense-db-165fe.firebasestorage.app',
    measurementId: 'G-FHDM8LWSF2',
  );
}
